Repository gardener/autoscaler, pull requests merged in 2023-12, with the labels that each got.

#263 Fix VPA pipelines
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#265 Ensure VPA pipelines use scripts for determining versions
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#267 Fix how write-vpa-version reads from stdin
  .ci/write-vpa-version.sh
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#257 Add options to `NodeGroupAutoscalingOptions` from `machineDeployment` annotations
  cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go
  cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider_test.go
  cluster-autoscaler/cloudprovider/mcm/mcm_manager.go
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/m

#273 Fix vpa version file path
  .ci/pipeline_definitions
  .ci/read-vpa-version.sh
  .ci/write-vpa-version.sh
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#274 Cherry-pick of #273: Fix vpa version file path
  .ci/pipeline_definitions
  .ci/read-vpa-version.sh
  .ci/write-vpa-version.sh
Labels: needs/ok-to-test, reviewed/lgtm, size/xs
