Repository gardener/autoscaler, pull requests merged in 2023-03, with the labels that each got.

#170 Configure Scanning Label for CA
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#160 No scale down for rolling update machineDeployment
  cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go
  cluster-autoscaler/cloudprovider/mcm/mcm_manager.go
  cluster-autoscaler/core/static_autoscaler.go
Labels: needs/ok-to-test, reviewed/lgtm, size/m

#188 Issue template and FAQ - autoscaler upstream sync
  .github/ISSUE_TEMPLATE/sync_request.md
  cluster-autoscaler/FAQ.md
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/m

#187 Updates in IT
  cluster-autoscaler/Makefile
  cluster-autoscaler/integration/framework.go
  cluster-autoscaler/integration/integration_test.go
  cluster-autoscaler/integration/usage.md
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/m

#190 Improve error message returned from `Nodes` method
  cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs
