Repository gardener/autoscaler, pull requests merged in 2023-04, with the labels that each got.

#196 Log error if `cluster-autoscaler-priority-expander` configmap missing
  cluster-autoscaler/Makefile
  cluster-autoscaler/expander/priority/priority.go
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, needs/cherry-pick

#197 Cherry pick upstream pr 5246 on 1.23
  cluster-autoscaler/Makefile
  cluster-autoscaler/expander/priority/priority.go
  cluster-autoscaler/expander/priority/priority_test.go
Labels: needs/ok-to-test, needs/review, size/xs

#202 Cherry pick upstream pr 5246 on 1.22
  cluster-autoscaler/Makefile
  cluster-autoscaler/expander/priority/priority.go
Labels: needs/ok-to-test, needs/review, size/xs

#200 Cherry pick upstream pr 5246 on 1.20
  cluster-autoscaler/Makefile
  cluster-autoscaler/expander/priority/priority.go
Labels: needs/ok-to-test, needs/review, size/xs

#203 Cherry pick PR #196 on 1.26
  cluster-autoscaler/Makefile
  cluster-autoscaler/expander/priority/priority.go
Labels: needs/ok-to-test, needs/review, size/xs

#195 Sync upstream rel v1.26
  cluster-autoscaler/SYNC-CHANGES/SYNC_CHANGES-1.26.md
  cluster-autoscaler/core/autoscaler.go
  cluster-autoscaler/go.mod
  cluster-autoscaler/go.sum
  cluster-autoscaler/main.go
  cluster-autoscaler/vendor/github.com/gardener/machine-controller-manager-provider-aws/pkg/aws/apis/aws_provider_spec.go
  cluster-autoscaler/vendor/modules.txt
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#209 Automated cherry pick of #160 on rel-v1.21: No scale down during rolling update
  cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go
  cluster-autoscaler/cloudprovider/mcm/mcm_manager.go
  cluster-autoscaler/core/static_autoscaler.go
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/m

#207 Automated cherry pick of #160 on rel-v1.23: No scale down during rolling update
  cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go
  cluster-autoscaler/cloudprovider/mcm/mcm_manager.go
  cluster-autoscaler/core/static_autoscaler.go
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/m

#206 Automated cherry pick of #160 on rel-v1.24: No scale down during rolling update
  cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go
  cluster-autoscaler/cloudprovider/mcm/mcm_manager.go
  cluster-autoscaler/core/static_autoscaler.go
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/m

#205 Automated cherry pick of #160 on rel-v1.25: No scale down during rolling update
  cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go
  cluster-autoscaler/cloudprovider/mcm/mcm_manager.go
  cluster-autoscaler/core/static_autoscaler.go
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/m
