Repository gardener/autoscaler, pull requests merged in 2023-06, with the labels that each got.

#228 Changed build to use go 1.20
  .ci/pipeline_definitions
  builder/Dockerfile
  cluster-autoscaler/Dockerfile
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#231 Clean up last imports of `k8s.io/klog` in favor of `k8s.io/klog/v2`
  cluster-autoscaler/cloudprovider/mcm/core_client_builder.go
  cluster-autoscaler/cloudprovider/mcm/machine_client_builder.go
  cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go
  cluster-autoscaler/go.mod
  cluster-autoscaler/go.sum
  cluster-autoscaler/vendor/k8s.io/klog/.travis.yml
  cluster-autoscaler/vendor/k8s.io/klog/CONTRIBUTING.md
  cluster-autoscaler/vendor/k8s.io/klog/LICENSE
  cluster-autoscaler/vendor/k8s.io/klog/OWNERS
  cluster-autoscaler/vendor/k8s.io/klog/README.md
  cluster-autoscaler/vendor/k8s.io/klog/RELEASE.md
  cluster-autoscaler/vendor/k8s.io/klog/SECURITY_CONTACTS
  cluster-autoscaler/vendor/k8s.io/klog/code-of-conduct.md
  cluster-autoscaler/vendor/k8s.io/klog/klog.go
  cluster-autoscaler/vendor/k8s.io/klog/klog_file.go
  cluster-autoscaler/vendor/modules.txt
Labels: kind/cleanup, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xl

#238 Fixed print of version in logs
  cluster-autoscaler/Dockerfile
  cluster-autoscaler/main.go
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#237 Change default values for fields in `NodeGroupDifferenceRatios`
  cluster-autoscaler/config/autoscaling_options.go
  cluster-autoscaler/processors/nodegroupset/compare_nodegroups.go
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s
