Repository gardener/autoscaler, pull requests merged in 2023-01, with the labels that each got.

#168 [rel-v1.20] Cherry pick of #161: Build Multi-Arch Images
  .ci/build
  .ci/pipeline_definitions
  cluster-autoscaler/Dockerfile
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#167 [rel-v1.21] Cherry pick of #161: Build Multi-Arch Images
  .ci/build
  .ci/pipeline_definitions
  cluster-autoscaler/Dockerfile
Labels: needs/ok-to-test, needs/review, size/s

#166 [rel-v1.22] Cherry pick of #161: Build Multi-Arch Images
  .ci/build
  .ci/pipeline_definitions
  cluster-autoscaler/Dockerfile
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#165 [rel-v1.23] Cherry pick of #161: Build Multi-Arch Images
  .ci/build
  .ci/pipeline_definitions
  cluster-autoscaler/Dockerfile
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#164 [rel-v1.24] Cherry pick of #161: Build Multi-Arch Images
  .ci/build
  .ci/pipeline_definitions
  cluster-autoscaler/Dockerfile
Labels: needs/ok-to-test, needs/review, size/s

#162 [rel-v1.25] Cherry pick of #161: Build Multi-Arch Images
  .ci/build
  .ci/pipeline_definitions
  cluster-autoscaler/Dockerfile
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#169 Configure scanning-hint CD source label
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/lgtm, size/xs
