Repository gardener/autoscaler, pull requests merged in 2024-01, with the labels that each got.

#284 Fix: trigger VPA pipeline on changes in .ci folder
  .ci/pipeline_definitions
Labels: reviewed/ok-to-test, reviewed/lgtm, size/xs

#283 Disable rendering of pipeline
  .ci/pipeline_definitions
Labels: reviewed/ok-to-test, reviewed/lgtm, size/xs

#282 Disable rendering of pipeline
  .ci/pipeline_definitions
Labels: reviewed/ok-to-test, reviewed/lgtm, size/xs

#281 Disable rendering of pipeline
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#280 Disable rendering of pipeline
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#279 Remove `snapshot_ctx_repository` attr from pipeline definition
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#277 Remove `snapshot_ctx_repository` attr from pipeline definition
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#276 Remove `snapshot_ctx_repository` attr from pipeline definition
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#286 Remove CA pipeline from VPA release branch
  .ci/pipeline_definitions
Labels: reviewed/ok-to-test, reviewed/lgtm, size/s

#288 Remove unnecessary things from VPA pipeline
  .ci/pipeline_definitions
Labels: reviewed/ok-to-test, reviewed/lgtm, size/xs

#285 Remove VPA pipeline from mcm-provider branch
  .ci/pipeline_definitions
  .ci/read-vpa-version.sh
  .ci/write-vpa-version.sh
  hack/boilerplate/boilerplate.py
  vertical-pod-autoscaler/Dockerfile.admissioncontroller
  vertical-pod-autoscaler/Dockerfile.recommender
  vertical-pod-autoscaler/Dockerfile.updater
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/m

#289 Bring back VPA pipeline, but with render_pipeline: false
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s

#290 Bring back CA pipeline, but with render_pipeline: false
  .ci/pipeline_definitions
Labels: needs/review, reviewed/ok-to-test, size/s

#292 GCR -> Artifact-Registry
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#293 GCR -> Artifact-Registry
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#295 Disable pipeline for rel-0.10
  .ci/pipeline_definitions
Labels: reviewed/ok-to-test, reviewed/lgtm, size/xs

#294 GCR -> Artifact-Registry
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#296 GCR -> Artifact-Registry
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#291 Added failed machine to prevent scaledown
  cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider_test.go
  cluster-autoscaler/cloudprovider/mcm/mcm_manager.go
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/s
