Repository gardener/autoscaler, pull requests merged in 2024-03, with the labels that each got.

#299 Add logging in case we have minimum memory recommendations
  vertical-pod-autoscaler/pkg/recommender/logic/estimator.go
Labels: needs/review, reviewed/ok-to-test, size/xs

#300 Add logging for mcm cloud-provider methods
  cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#301 Cherrypick of https://github.com/gardener/autoscaler/pull/300
  cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs
