Repository gardener/autoscaler, pull requests merged in 2024-07, with the labels that each got.

#309 Populate instance status state when `machine.Status.LastOperation.Type` is `Create`
  cluster-autoscaler/cloudprovider/mcm/mcm_manager.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#310 Updated NodeGroupAutoscalingOptions to now include all options
  cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go
  cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider_test.go
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#312 Cherry-pick of #309
  cluster-autoscaler/cloudprovider/mcm/mcm_manager.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#313 [cherry-pick v1.29] Updated NodeGroupAutoscalingOptions to now include all options (#310)
  cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go
  cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider_test.go
Labels: needs/ok-to-test, needs/review, size/s

#314 [cherry-pick v1.28] Updated NodeGroupAutoscalingOptions to now include all options (#310)
  cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider.go
  cluster-autoscaler/cloudprovider/mcm/mcm_cloud_provider_test.go
Labels: needs/ok-to-test, needs/review, size/s

#315 [cherry-pick 1.27] populate instance status state when machine lastOperation is Create
  cluster-autoscaler/cloudprovider/mcm/mcm_manager.go
Labels: needs/ok-to-test, needs/review, reviewed/lgtm, size/xs

#316 [cherry-pick 1.28] populate instance status state when machine lastOperation is Create
  cluster-autoscaler/cloudprovider/mcm/mcm_manager.go
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#287 Added arch
  cluster-autoscaler/cloudprovider/mcm/mcm_manager.go
Labels: needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs
